'use strict';

3 AUTENTICIDAD, LO Q AMAS: LEER, APRENDER Y ENSEÑAR, PROGRAMAR, COMUNICAR, MUSICA, CANTAR

6 DEPENDENCIA, PA Q SOY BUENO: ENSEÑAR, COMUNICAR, LÓGICA, RAZONAR, PROGRAMAR

9 OPORTUNIDADES, POR LO Q PUEDEN PAGARME: DAR CLASES, DAR CHARLAS, LOCUTAR

12 SOLO, LO Q EL MUNDO NECESITA: PROGRESAR, APRENDER, ABOLIR EL ESTADO

IKIGAI
ME COMPROMETO A SER LO MÁS GRANDE Y MEJOR Q PUEDA SER Y A IR POR MIS OBJETIVOS Y CUMPLIR MIS SUEÑOS AYUDANDO A LOS DEMAS: LOCUCION, CANTAR, PROGRAMAR, ENSEÑAR, EMPRENDER, DAR CHARLAS, ESTUDIAR ECONOMIA E ING, SER POLIGLOTA

